version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: 884709943476.dkr.ecr.us-east-2.amazonaws.com/django-ec2:web
    command: gunicorn dictmasher.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    # depends_on:
    #   - db
  # db:
  #   image: postgres:12.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env.prod.db

  nginx:
    build: nginx
    image: 884709943476.dkr.ecr.us-east-2.amazonaws.com/django-ec2:nginx-proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web


volumes:
  # postgres_data:
  static_volume:
