# Generated by Django 3.2 on 2021-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lang', models.CharField(choices=[('EN', 'EN'), ('DE', 'DE'), ('TRANS', 'TRANS')], max_length=5)),
                ('type', models.CharField(choices=[('HTML', 'HTML'), ('API', 'API')], max_length=5)),
                ('div_id', models.CharField(max_length=20)),
                ('base_url', models.CharField(max_length=500)),
            ],
        ),
    ]
