# Generated by Django 3.2 on 2021-04-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_de_settings_en_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled_de', models.BooleanField()),
                ('is_enabled_en', models.BooleanField()),
                ('is_trimmed', models.BooleanField()),
                ('order_de', models.IntegerField()),
                ('order_en', models.IntegerField()),
                ('dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.dictionary')),
            ],
        ),
        migrations.DeleteModel(
            name='DE_Settings',
        ),
        migrations.DeleteModel(
            name='EN_Settings',
        ),
    ]
