# Generated by Django 3.2 on 2021-04-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210422_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='is_trimmed',
        ),
        migrations.AddField(
            model_name='settings',
            name='is_trimmed_de',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='is_trimmed_en',
            field=models.BooleanField(default=True),
        ),
    ]
