# Generated by Django 3.2 on 2021-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_settings_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='dependencies',
            field=models.JSONField(null=True),
        ),
    ]
